### ISSUE TITLE
v2: Error: Cannot find module 'asn1.js'

### ISSUE THREAD

**Issue by moltar** [codecov/codecov-action#427]
Since upgrading to v2, getting the following:

```
Run codecov/codecov-action@v2
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'asn1.js'
Require stack:
- /home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at o (/home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:6960:200)
    at /home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:6960:391
    at Object.<anonymous> (/home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:38030:27)
    at Object.108.../../config (/home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:38601:4)
    at o (/home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:6960:340)
    at /home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js:6960:391 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/_actions/codecov/codecov-action/v2/dist/index.js'
  ]
}
```

Any ideas?

**Comment by hoc081098** [comment]
Same issue

**Comment by HonkingGoose** [comment]
Hi @moltar and @hoc081098 did you try upgrading to version `2.0.1` of this action? According to the developer that should fix the problem:

> This should be resolved in `2.0.1` Sorry about that

https://github.com/codecov/codecov-action/issues/423#issuecomment-882672963

**Comment by thomasrockhu** [comment]
This should be resolved in `2.0.1` @moltar @hoc081098
