### ISSUE TITLE
`Error: Runner "composite" does not implemented` after upgrade to v5

### ISSUE THREAD

**Issue by f0uriest** [codecov/codecov-action#1719]
We use `codecov-action` inside another action that tries in several times in a loop (to prevent failing CI due to intermittent connection issues with the upload). 

This seems to be failing after we upgraded to v5 with the message
```
Error: Runner "composite" does not implemented.
```

Logs: https://github.com/PlasmaControl/DESC/actions/runs/12259667401/job/34202389650

**Comment by thomasrockhu-codecov** [comment]
@f0uriest this is a problem with `Wandalen/wretry.action`, it's implementation only work on JS actions.

**Comment by f0uriest** [comment]
I tried a few different version of Wandalan/wretry.action and none seemed to work. For now we've gotten rid of the retry and seems to be ok. 

Given that v5 of codecov-action just wraps the CLI, and the CLI itself has options for retrying, would it be possible to plumb that option out?

**Comment by thomasrockhu-codecov** [comment]
@f0uriest maybe I'm missing something, but I'm fairly sure the CLI does not have retry options exposed. If you see that, do you mind pointing it out?

**Comment by thomasrockhu-codecov** [comment]
@f0uriest going to close this out now, let me know if the problem persists
